name: stars_lib
channels:
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=hb4e5f40_0
  - hypothesis=5.5.4=py_0
  - importlib_metadata=1.5.0=py37_0
  - intel-openmp=2019.4=233
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=8.2.0=py_0
  - ncurses=6.2=h0a44026_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1f=h1de35cc_0
  - packaging=20.3=py_0
  - pip=20.0.2=py37_1
  - pluggy=0.13.1=py37_0
  - psutil=5.7.0=py37h1de35cc_0
  - py=1.8.1=py_0
  - pyparsing=2.4.6=py_0
  - pytest=5.4.1=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.1=py_0
  - readline=8.0=h1de35cc_0
  - scipy=1.4.1=py37h9fa6033_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sortedcontainers=2.1.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py37h1de35cc_1
  - wcwidth=0.1.9=py_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/lawsmith/anaconda/envs/py37

